[package]
name = "typst-ansi-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { git = "https://github.com/PgBiel/iced", branch = "select-all", features = ["svg"] }
